service:
  112924:  # Interesting Game
    service_id: "112924"
    short_code: "90440"
    keyword: "CZ197"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://interest.3499games.com"
    service_name: "Interesting GAME"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    notification_url: "http://cz.foxseekmedia.com/notification"
    start_sub_return_url: "http://interest.3499games.com/cz/welcome"
    merchant_password: "NcLhwtLvxWS1shx"
    prompt_content_args_cs_old: "Zaslate prosim ANO na cislo 9440. %v %v %v %v. "
    prompt_content_args_cs: "odkaz: %v"
    prompt_content_args_en_old: "Please send ANO to 90440. %v %v %v %v. "
    prompt_content_args_en: "link: %v"
    merchant_id: "200304"
    server_order: "112924"
    price: "99"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2
  112925:  # Game Center
    service_id: "112925"
    short_code: "90440"
    keyword: "CZ198"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://gc.mrgameloft.com"
    service_name: "Game Center"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    notification_url: "http://cz.foxseekmedia.com/notification"
    start_sub_return_url: "http://gc.mrgameloft.com/welcome"
    prompt_content_args_cs: "odkaz: %v"
    prompt_content_args_cs_old: "Zaslate prosim ANO na cislo 9440. Cena zpravy %v Kc s DPH za sluzbu %v. Pro zruseni posli SMS ve tvaru STOP sluzba na cislo %v. Vice info posli SMS HELP na %v. "
    prompt_content_args_en: "link: %v "
    prompt_content_args_en_old: "Please send ANO to 90440. %v"
    merchant_password: "NcLhwtLvxWS1shx"
    merchant_id: "200304"
    server_order: "112925"
    price: "99"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2
  112926:  # FNGame
    service_id: "112926"
    short_code: "90440"
    keyword: "CZ199"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://fn.3499games.com"
    service_name: "FNGame"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    notification_url: "http://cz.foxseekmedia.com/notification"
    start_sub_return_url: "http://fn.3499games.com/welcome"
    prompt_content_args_cs: "odkaz: %v"
    prompt_content_args_cs_old: "Zaslate prosim ANO na cislo 9440. Cena zpravy %v Kc s DPH za sluzbu %v. Pro zruseni posli SMS ve tvaru STOP sluzba na cislo %v. Vice info posli SMS HELP na %v. "
    prompt_content_args_en: "link: %v"
    prompt_content_args_en_old: "Please send ANO to 90440. Price of the message %v CZK with VAT for the service %v. To cancel, send an SMS in the form of STOP service to the number %v. More info send SMS HELP to %v. "
    merchant_password: "NcLhwtLvxWS1shx"
    merchant_id: "200304"
    server_order: "112926"
    price: "99"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2

