service:
  90440-CZ197:  # Interesting Game
    service_id: "90440-CZ197"
    short_code: "90440"
    keyword: "CZ197"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://fun.3499games.com"
    service_name: "Interesting GAME"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    merchant_password: "X2X0FAF37X2yMF9"
    merchant_id: "200304"
    server_order: "112924"
    price: "10"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2
  90440-CZ198:  # Game Center
    service_id: "90440-CZ198"
    short_code: "90440"
    keyword: "CZ198"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://gc.mrgameloft.com"
    service_name: "Game Center"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    merchant_password: "X2X0FAF37X2yMF9"
    merchant_id: "200304"
    server_order: "112925"
    price: "10"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2
  90440-CZ199:  # FNGame
    service_id: "90440-CZ199"
    short_code: "90440"
    keyword: "CZ199"
    dock_url: "http://cz.foxseekmedia.com"
    content_url: "http://fn.3499games.com"
    service_name: "FNGame"
    server_url: "https://services.dimoco.at/smart/payment"
    user_api_url: "https://services.dimoco.at/smart/userpayment"
    merchant_password: "X2X0FAF37X2yMF9"
    merchant_id: "200304"
    server_order: "112926"
    price: "10"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2

