service:
  90440-CZ197:  # 游戏服务
    service_id: "90440-CZ197"
    short_code: "90440"
    keyword: "CZ197"
    content_url: "http://fun.3499games.com/"
    service_name: "FunGameInteresting"
    price: "10"
    country: "CZ"
    limit_sub_num: 2000
    camp_id: 2

